[package]
name = "sleitnick/observers"
description = "A collection of observer utility functions"
version = "0.2.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["lib", "lib/**", "wally.toml", "wally.lock", "default.project.json", "LICENSE.md"]
